<?php
/**
 * Plugin Name: Easy Mailchimp Opt-in
 * Plugin URI: https://wordpress.org/plugins/easy-mailchimp-opt-in/
 * Description: Premium Mailchimp form builder with live preview, responsive templates, AJAX subscriptions, GDPR, spam protection, analytics, Gutenberg and Elementor support.
 * Version: 3.1.0
 * Requires at least: 6.2
 * Requires PHP: 7.4
 * Author: Mahfuzar
 * Author URI: https://mahfuzar.info
 * License: GPLv2 or later
 * Text Domain: easy-mailchimp-optin
 */
if ( ! defined( 'ABSPATH' ) ) exit;

final class EMO_Premium {
	const VERSION='3.1.0', SETTINGS='emo_settings', FORMS='emo_forms', STATS='emo_stats';
	private static $instance;
	public static function instance(){ return self::$instance ?: (self::$instance=new self()); }
	private function __construct(){
		add_action('admin_menu',[$this,'menu']); add_action('admin_init',[$this,'register_settings']);
		add_action('admin_enqueue_scripts',[$this,'admin_assets']); add_action('wp_enqueue_scripts',[$this,'frontend_assets']);
		add_action('wp_ajax_emo_test_connection',[$this,'ajax_test_connection']); add_action('wp_ajax_emo_audience_schema',[$this,'ajax_audience_schema']);
		add_action('wp_ajax_emo_subscribe',[$this,'ajax_subscribe']); add_action('wp_ajax_nopriv_emo_subscribe',[$this,'ajax_subscribe']);
		add_action('admin_post_emo_save_form',[$this,'save_form']); add_action('admin_post_emo_delete_form',[$this,'delete_form']);
		add_action('admin_post_emo_export_forms',[$this,'export_forms']); add_action('admin_post_emo_import_forms',[$this,'import_forms']);
		add_shortcode('easy_mailchimp_form',[$this,'shortcode']); add_shortcode('mailchimp',[$this,'legacy_shortcode']);
		add_action('init',[$this,'register_block']); add_action('elementor/widgets/register',[$this,'register_elementor_widget']);
	}
	public function register_settings(){ register_setting('emo_settings_group',self::SETTINGS,['sanitize_callback'=>[$this,'sanitize_settings']]); }
	public function sanitize_settings($in){ return [
		'api_key'=>sanitize_text_field($in['api_key']??''),'spam_provider'=>in_array($in['spam_provider']??'honeypot',['honeypot','turnstile','recaptcha'],true)?$in['spam_provider']:'honeypot',
		'turnstile_site_key'=>sanitize_text_field($in['turnstile_site_key']??''),'turnstile_secret_key'=>sanitize_text_field($in['turnstile_secret_key']??''),
		'recaptcha_site_key'=>sanitize_text_field($in['recaptcha_site_key']??''),'recaptcha_secret_key'=>sanitize_text_field($in['recaptcha_secret_key']??'') ]; }
	private function settings(){ return wp_parse_args(get_option(self::SETTINGS,[]),['api_key'=>'','spam_provider'=>'honeypot','turnstile_site_key'=>'','turnstile_secret_key'=>'','recaptcha_site_key'=>'','recaptcha_secret_key'=>'']); }
	private function forms(){ $f=get_option(self::FORMS,[]); return is_array($f)?$f:[]; }
	private function templates(){ return ['classic'=>'Classic','minimal'=>'Minimal','card'=>'Card','dark'=>'Dark','inline'=>'Inline','gradient'=>'Gradient','split'=>'Split','bordered'=>'Bordered','soft'=>'Soft','bold'=>'Bold']; }
	private function defaults(){ return ['id'=>'','name'=>'','audience_id'=>'','template'=>'classic','title'=>'Join our newsletter','description'=>'Get useful updates in your inbox.','button_text'=>'Subscribe','success_message'=>'Thank you for subscribing.','show_first'=>1,'show_last'=>0,'show_phone'=>0,'gdpr'=>1,'gdpr_text'=>'I agree to receive email updates.','double_opt_in'=>1,'tags'=>'','groups'=>[],'field_map'=>[],'redirect_url'=>'','accent_color'=>'#635bff','background_color'=>'#ffffff','text_color'=>'#172033','border_radius'=>14,'custom_css'=>'']; }
	public function menu(){ add_menu_page('Easy Mailchimp','Easy Mailchimp','manage_options','easy-mailchimp-optin',[$this,'settings_page'],'dashicons-email-alt2',58); add_submenu_page('easy-mailchimp-optin','Forms','Forms','manage_options','easy-mailchimp-forms',[$this,'forms_page']); add_submenu_page('easy-mailchimp-optin','Analytics','Analytics','manage_options','easy-mailchimp-analytics',[$this,'analytics_page']); add_submenu_page('easy-mailchimp-optin','Import / Export','Import / Export','manage_options','easy-mailchimp-tools',[$this,'tools_page']); }
	public function admin_assets($hook){ if(strpos($hook,'easy-mailchimp')===false)return; wp_enqueue_style('emo-admin',plugins_url('assets/css/admin.css',__FILE__),[],self::VERSION); wp_enqueue_style('emo-forms',plugins_url('assets/css/forms.css',__FILE__),[],self::VERSION); wp_enqueue_script('emo-admin',plugins_url('assets/js/admin.js',__FILE__),['jquery'],self::VERSION,true); wp_localize_script('emo-admin','emoAdmin',['ajax'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('emo_admin'),'savedGroups'=>[],'savedMap'=>[]]); }
	public function frontend_assets(){ wp_register_style('emo-forms',plugins_url('assets/css/forms.css',__FILE__),[],self::VERSION); wp_register_script('emo-forms',plugins_url('assets/js/forms.js',__FILE__),[],self::VERSION,true); wp_localize_script('emo-forms','emoForms',['ajax'=>admin_url('admin-ajax.php')]); }
	private function dc($key){ $p=explode('-',trim($key)); return count($p)>1?sanitize_key(end($p)):''; }
	private function api($method,$path,$body=null){ $s=$this->settings();$key=trim($s['api_key']);$dc=$this->dc($key);if(!$key||!$dc)return new WP_Error('emo_api','Enter a valid Mailchimp API key.');$a=['method'=>strtoupper($method),'timeout'=>25,'headers'=>['Authorization'=>'Basic '.base64_encode('wordpress:'.$key),'Content-Type'=>'application/json']];if($body!==null)$a['body']=wp_json_encode($body);$r=wp_remote_request('https://'.$dc.'.api.mailchimp.com/3.0/'.ltrim($path,'/'),$a);if(is_wp_error($r))return$r;$code=wp_remote_retrieve_response_code($r);$d=json_decode(wp_remote_retrieve_body($r),true);if($code<200||$code>=300)return new WP_Error('emo_mailchimp',$d['detail']??'Mailchimp API request failed.',['status'=>$code]);return is_array($d)?$d:[]; }
	private function audiences(){ $r=$this->api('GET','lists?count=100&fields=lists.id,lists.name,lists.stats.member_count'); return is_wp_error($r)?$r:($r['lists']??[]); }
	public function settings_page(){ $s=$this->settings(); ?><div class="wrap emo-wrap"><div class="emo-page-head"><div><h1>Easy Mailchimp</h1><p>Connect your account and configure global spam protection.</p></div><button class="button" id="emo-test-connection">Test connection</button></div><div class="emo-card emo-settings-card"><form method="post" action="options.php"><?php settings_fields('emo_settings_group'); ?><div class="emo-settings-grid"><label><span>Mailchimp API key</span><input type="password" name="<?php echo esc_attr(self::SETTINGS); ?>[api_key]" value="<?php echo esc_attr($s['api_key']); ?>" autocomplete="new-password"></label><label><span>Spam protection</span><select name="<?php echo esc_attr(self::SETTINGS); ?>[spam_provider]"><?php foreach(['honeypot'=>'Honeypot','turnstile'=>'Cloudflare Turnstile','recaptcha'=>'Google reCAPTCHA v2'] as $k=>$v)printf('<option value="%s" %s>%s</option>',esc_attr($k),selected($s['spam_provider'],$k,false),esc_html($v));?></select></label><label><span>Turnstile site key</span><input name="<?php echo esc_attr(self::SETTINGS); ?>[turnstile_site_key]" value="<?php echo esc_attr($s['turnstile_site_key']); ?>"></label><label><span>Turnstile secret</span><input type="password" name="<?php echo esc_attr(self::SETTINGS); ?>[turnstile_secret_key]" value="<?php echo esc_attr($s['turnstile_secret_key']); ?>"></label><label><span>reCAPTCHA site key</span><input name="<?php echo esc_attr(self::SETTINGS); ?>[recaptcha_site_key]" value="<?php echo esc_attr($s['recaptcha_site_key']); ?>"></label><label><span>reCAPTCHA secret</span><input type="password" name="<?php echo esc_attr(self::SETTINGS); ?>[recaptcha_secret_key]" value="<?php echo esc_attr($s['recaptcha_secret_key']); ?>"></label></div><?php submit_button('Save settings'); ?></form><span id="emo-test-result"></span></div></div><?php }
	public function ajax_test_connection(){ check_ajax_referer('emo_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error('Unauthorized');$r=$this->api('GET','ping');is_wp_error($r)?wp_send_json_error($r->get_error_message()):wp_send_json_success('Connection successful.'); }
	public function ajax_audience_schema(){ check_ajax_referer('emo_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error('Unauthorized');$id=sanitize_text_field($_POST['audience_id']??'');if(!$id)wp_send_json_success(['groups'=>[],'merge_fields'=>[]]);$cats=$this->api('GET','lists/'.rawurlencode($id).'/interest-categories?count=100');$groups=[];if(!is_wp_error($cats))foreach($cats['categories']??[] as $cat){$ints=$this->api('GET','lists/'.rawurlencode($id).'/interest-categories/'.rawurlencode($cat['id']).'/interests?count=100');if(!is_wp_error($ints))$groups[]=['id'=>$cat['id'],'title'=>$cat['title'],'type'=>$cat['type'],'interests'=>array_map(function($x){return['id'=>$x['id'],'name'=>$x['name']];},$ints['interests']??[])];}$mf=$this->api('GET','lists/'.rawurlencode($id).'/merge-fields?count=100');wp_send_json_success(['groups'=>$groups,'merge_fields'=>is_wp_error($mf)?[]:array_map(function($x){return['tag'=>$x['tag'],'name'=>$x['name'],'type'=>$x['type']];},$mf['merge_fields']??[])]); }
	public function forms_page(){ $forms=$this->forms();$id=sanitize_key($_GET['edit']??'');$f=wp_parse_args($forms[$id]??[],$this->defaults());$aud=$this->audiences();wp_localize_script('emo-admin','emoFormData',['savedGroups'=>(array)$f['groups'],'savedMap'=>(array)$f['field_map']]); ?>
	<div class="wrap emo-wrap"><div class="emo-page-head"><div><h1><?php echo $id?'Edit form':'Create form'; ?></h1><p>Build and preview your Mailchimp form in real time.</p></div><?php if($id):?><code>[easy_mailchimp_form id="<?php echo esc_attr($id); ?>"]</code><?php endif;?></div><div class="emo-builder"><form class="emo-builder-panel" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="emo_save_form"><input type="hidden" name="form_id" value="<?php echo esc_attr($f['id']); ?>"><?php wp_nonce_field('emo_save_form'); ?>
	<div class="emo-section"><h2>Form</h2><div class="emo-two"><label><span>Form name</span><input required name="name" value="<?php echo esc_attr($f['name']); ?>"></label><label><span>Audience</span><select required id="emo-audience" name="audience_id"><option value="">Select audience</option><?php if(!is_wp_error($aud))foreach($aud as $a)printf('<option value="%s" %s>%s (%d)</option>',esc_attr($a['id']),selected($f['audience_id'],$a['id'],false),esc_html($a['name']),intval($a['stats']['member_count']??0));?></select></label></div><div class="emo-two"><label><span>Template</span><select class="emo-live" name="template"><?php foreach($this->templates() as $k=>$v)printf('<option value="%s" %s>%s</option>',esc_attr($k),selected($f['template'],$k,false),esc_html($v));?></select></label><label><span>Button text</span><input class="emo-live" name="button_text" value="<?php echo esc_attr($f['button_text']); ?>"></label></div><label><span>Title</span><input class="emo-live" name="title" value="<?php echo esc_attr($f['title']); ?>"></label><label><span>Description</span><textarea class="emo-live" name="description" rows="2"><?php echo esc_textarea($f['description']); ?></textarea></label></div>
	<div class="emo-section"><h2>Fields & consent</h2><div class="emo-checks"><label><input class="emo-live" type="checkbox" name="show_first" value="1" <?php checked($f['show_first']);?>> First name</label><label><input class="emo-live" type="checkbox" name="show_last" value="1" <?php checked($f['show_last']);?>> Last name</label><label><input class="emo-live" type="checkbox" name="show_phone" value="1" <?php checked($f['show_phone']);?>> Phone</label><label><input class="emo-live" type="checkbox" name="gdpr" value="1" <?php checked($f['gdpr']);?>> GDPR consent</label><label><input type="checkbox" name="double_opt_in" value="1" <?php checked($f['double_opt_in']);?>> Double opt-in</label></div><label><span>Consent text</span><input class="emo-live" name="gdpr_text" value="<?php echo esc_attr($f['gdpr_text']); ?>"></label></div>
	<div class="emo-section"><h2>Mailchimp options</h2><label><span>Tags <small>Comma separated</small></span><input name="tags" value="<?php echo esc_attr($f['tags']); ?>"></label><div id="emo-groups"><p class="description">Select an audience to load its interest groups.</p></div><div id="emo-merge-fields"><p class="description">Audience merge fields will appear here.</p></div></div>
	<div class="emo-section"><h2>Style</h2><div class="emo-four"><label><span>Accent</span><input class="emo-live" type="color" name="accent_color" value="<?php echo esc_attr($f['accent_color']); ?>"></label><label><span>Background</span><input class="emo-live" type="color" name="background_color" value="<?php echo esc_attr($f['background_color']); ?>"></label><label><span>Text</span><input class="emo-live" type="color" name="text_color" value="<?php echo esc_attr($f['text_color']); ?>"></label><label><span>Radius</span><input class="emo-live" type="number" min="0" max="60" name="border_radius" value="<?php echo intval($f['border_radius']); ?>"></label></div><label><span>Custom CSS <small>Use <code>{{FORM}}</code> as the form selector.</small></span><textarea name="custom_css" rows="5" placeholder="{{FORM}} .emo-submit { font-size: 18px; }"><?php echo esc_textarea($f['custom_css']); ?></textarea></label></div>
	<div class="emo-section"><h2>After submission</h2><div class="emo-two"><label><span>Success message</span><input name="success_message" value="<?php echo esc_attr($f['success_message']); ?>"></label><label><span>Redirect URL <small>Optional</small></span><input type="url" name="redirect_url" value="<?php echo esc_attr($f['redirect_url']); ?>"></label></div></div><div class="emo-sticky-actions"><?php submit_button($id?'Update form':'Create form','primary','submit',false);?></div></form>
	<aside class="emo-builder-side"><div class="emo-preview-card"><div class="emo-preview-head"><strong>Live preview</strong><span>Responsive</span></div><div id="emo-preview" class="emo-form emo-template-<?php echo esc_attr($f['template']); ?>" style="--emo-accent:<?php echo esc_attr($f['accent_color']); ?>;--emo-bg:<?php echo esc_attr($f['background_color']); ?>;--emo-text:<?php echo esc_attr($f['text_color']); ?>;--emo-radius:<?php echo intval($f['border_radius']); ?>px"><form><h3><?php echo esc_html($f['title']); ?></h3><p class="emo-description"><?php echo esc_html($f['description']); ?></p><div class="emo-fields"><label class="preview-first"><span>First name</span><input></label><label class="preview-last"><span>Last name</span><input></label><label class="preview-phone"><span>Phone</span><input></label><label><span>Email</span><input type="email"></label></div><label class="emo-gdpr preview-gdpr"><input type="checkbox"><span><?php echo esc_html($f['gdpr_text']); ?></span></label><button type="button"><span><?php echo esc_html($f['button_text']); ?></span></button></form></div></div><div class="emo-card emo-existing"><h2>Existing forms</h2><?php if(!$forms)echo'<p>No forms yet.</p>';foreach($forms as $x)echo'<div class="emo-form-row"><div><strong>'.esc_html($x['name']).'</strong><small>'.esc_html($this->templates()[$x['template']]??$x['template']).'</small></div><code>[easy_mailchimp_form id="'.esc_attr($x['id']).'"]</code><div><a class="button button-small" href="'.esc_url(admin_url('admin.php?page=easy-mailchimp-forms&edit='.$x['id'])).'">Edit</a> <a class="button button-small emo-delete" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=emo_delete_form&id='.$x['id']),'emo_delete_form')).'">Delete</a></div></div>';?></div></aside></div></div><?php }
	public function save_form(){ if(!current_user_can('manage_options'))wp_die('Unauthorized');check_admin_referer('emo_save_form');$forms=$this->forms();$id=sanitize_key($_POST['form_id']??'');if(!$id)$id='form-'.wp_generate_password(8,false,false);$groups=[];foreach((array)($_POST['groups']??[]) as $gid=>$v)$groups[sanitize_text_field($gid)]=!empty($v);$map=[];foreach((array)($_POST['field_map']??[]) as $tag=>$field){$tag=sanitize_key($tag);$field=sanitize_key($field);if($tag&&$field)$map[$tag]=$field;}$css=current_user_can('unfiltered_html')?wp_unslash($_POST['custom_css']??''):'';$forms[$id]=['id'=>$id,'name'=>sanitize_text_field($_POST['name']??''),'audience_id'=>sanitize_text_field($_POST['audience_id']??''),'template'=>array_key_exists($_POST['template']??'',$this->templates())?sanitize_key($_POST['template']):'classic','title'=>sanitize_text_field($_POST['title']??''),'description'=>sanitize_textarea_field($_POST['description']??''),'button_text'=>sanitize_text_field($_POST['button_text']??'Subscribe'),'success_message'=>sanitize_text_field($_POST['success_message']??'Thank you.'),'show_first'=>empty($_POST['show_first'])?0:1,'show_last'=>empty($_POST['show_last'])?0:1,'show_phone'=>empty($_POST['show_phone'])?0:1,'gdpr'=>empty($_POST['gdpr'])?0:1,'gdpr_text'=>sanitize_text_field($_POST['gdpr_text']??''),'double_opt_in'=>empty($_POST['double_opt_in'])?0:1,'tags'=>sanitize_text_field($_POST['tags']??''),'groups'=>$groups,'field_map'=>$map,'redirect_url'=>esc_url_raw($_POST['redirect_url']??''),'accent_color'=>sanitize_hex_color($_POST['accent_color']??'')?:'#635bff','background_color'=>sanitize_hex_color($_POST['background_color']??'')?:'#ffffff','text_color'=>sanitize_hex_color($_POST['text_color']??'')?:'#172033','border_radius'=>min(60,max(0,intval($_POST['border_radius']??14))),'custom_css'=>$css];update_option(self::FORMS,$forms,false);wp_safe_redirect(admin_url('admin.php?page=easy-mailchimp-forms&edit='.$id.'&saved=1'));exit; }
	public function delete_form(){if(!current_user_can('manage_options'))wp_die('Unauthorized');check_admin_referer('emo_delete_form');$f=$this->forms();unset($f[sanitize_key($_GET['id']??'')]);update_option(self::FORMS,$f,false);wp_safe_redirect(admin_url('admin.php?page=easy-mailchimp-forms'));exit;}
	private function custom_css($f,$id){$css=(string)($f['custom_css']??'');if(!$css)return'';$selector='.emo-form[data-form="'.esc_attr($id).'"]';return str_replace('{{FORM}}',$selector,$css);}
	public function shortcode($atts){$id=sanitize_key(shortcode_atts(['id'=>''],$atts)['id']);$forms=$this->forms();if(empty($forms[$id]))return current_user_can('manage_options')?'<p>Easy Mailchimp form not found.</p>':'';$f=wp_parse_args($forms[$id],$this->defaults());wp_enqueue_style('emo-forms');wp_enqueue_script('emo-forms');$this->stat($id,'views');$s=$this->settings();$style='--emo-accent:'.$f['accent_color'].';--emo-bg:'.$f['background_color'].';--emo-text:'.$f['text_color'].';--emo-radius:'.intval($f['border_radius']).'px';ob_start();if($f['custom_css'])echo'<style>'.wp_strip_all_tags($this->custom_css($f,$id)).'</style>';?><div class="emo-form emo-template-<?php echo esc_attr($f['template']);?>" data-form="<?php echo esc_attr($id);?>" style="<?php echo esc_attr($style);?>"><form class="emo-ajax-form"><input type="hidden" name="action" value="emo_subscribe"><input type="hidden" name="form_id" value="<?php echo esc_attr($id);?>"><input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('emo_subscribe_'.$id));?>"><input class="emo-hp" type="text" name="website" tabindex="-1" autocomplete="off"><h3><?php echo esc_html($f['title']);?></h3><p class="emo-description"><?php echo esc_html($f['description']);?></p><div class="emo-fields"><?php if($f['show_first']):?><label><span>First name</span><input name="first_name" autocomplete="given-name"></label><?php endif;if($f['show_last']):?><label><span>Last name</span><input name="last_name" autocomplete="family-name"></label><?php endif;if($f['show_phone']):?><label><span>Phone</span><input name="phone" type="tel" autocomplete="tel"></label><?php endif;?><label class="emo-email"><span>Email</span><input required name="email" type="email" autocomplete="email"></label></div><?php if($f['gdpr']):?><label class="emo-gdpr"><input required type="checkbox" name="gdpr" value="1"><span><?php echo esc_html($f['gdpr_text']);?></span></label><?php endif;?><?php if($s['spam_provider']==='turnstile'&&$s['turnstile_site_key']):?><div class="cf-turnstile" data-sitekey="<?php echo esc_attr($s['turnstile_site_key']);?>"></div><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script><?php elseif($s['spam_provider']==='recaptcha'&&$s['recaptcha_site_key']):?><div class="g-recaptcha" data-sitekey="<?php echo esc_attr($s['recaptcha_site_key']);?>"></div><script src="https://www.google.com/recaptcha/api.js" async defer></script><?php endif;?><button class="emo-submit" type="submit"><span><?php echo esc_html($f['button_text']);?></span></button><div class="emo-message" role="status" aria-live="polite"></div></form></div><?php return ob_get_clean(); }
	public function legacy_shortcode($atts){$forms=$this->forms();$first=reset($forms);return$first?$this->shortcode(['id'=>$first['id']]):'';}
	private function verify_spam(){$s=$this->settings();if(!empty($_POST['website']))return false;if($s['spam_provider']==='honeypot')return true;$token=$s['spam_provider']==='turnstile'?sanitize_text_field($_POST['cf-turnstile-response']??''):sanitize_text_field($_POST['g-recaptcha-response']??'');$secret=$s['spam_provider']==='turnstile'?$s['turnstile_secret_key']:$s['recaptcha_secret_key'];if(!$token||!$secret)return false;$url=$s['spam_provider']==='turnstile'?'https://challenges.cloudflare.com/turnstile/v0/siteverify':'https://www.google.com/recaptcha/api/siteverify';$r=wp_remote_post($url,['timeout'=>15,'body'=>['secret'=>$secret,'response'=>$token,'remoteip'=>$_SERVER['REMOTE_ADDR']??'']]);if(is_wp_error($r))return false;$d=json_decode(wp_remote_retrieve_body($r),true);return!empty($d['success']);}
	public function ajax_subscribe(){$id=sanitize_key($_POST['form_id']??'');if(!wp_verify_nonce(sanitize_text_field($_POST['nonce']??''),'emo_subscribe_'.$id))wp_send_json_error(['message'=>'Security check failed.']);$forms=$this->forms();if(empty($forms[$id]))wp_send_json_error(['message'=>'Form not found.']);$f=wp_parse_args($forms[$id],$this->defaults());if(!$this->verify_spam())wp_send_json_error(['message'=>'Spam verification failed.']);$email=sanitize_email($_POST['email']??'');if(!is_email($email))wp_send_json_error(['message'=>'Enter a valid email address.']);if($f['gdpr']&&empty($_POST['gdpr']))wp_send_json_error(['message'=>'Please accept the consent checkbox.']);$merge=['FNAME'=>sanitize_text_field($_POST['first_name']??''),'LNAME'=>sanitize_text_field($_POST['last_name']??'')];if($f['show_phone'])$merge['PHONE']=sanitize_text_field($_POST['phone']??'');foreach((array)$f['field_map'] as $tag=>$field)if(isset($_POST[$field]))$merge[strtoupper(sanitize_key($tag))]=sanitize_text_field(wp_unslash($_POST[$field]));$body=['email_address'=>$email,'status_if_new'=>$f['double_opt_in']?'pending':'subscribed','status'=>$f['double_opt_in']?'pending':'subscribed','merge_fields'=>array_filter($merge,function($v){return$v!=='';})];if($f['groups'])$body['interests']=(object)$f['groups'];$r=$this->api('PUT','lists/'.rawurlencode($f['audience_id']).'/members/'.md5(strtolower($email)),$body);if(is_wp_error($r))wp_send_json_error(['message'=>$r->get_error_message()]);$tags=array_filter(array_map('trim',explode(',',$f['tags'])));if($tags)$this->api('POST','lists/'.rawurlencode($f['audience_id']).'/members/'.md5(strtolower($email)).'/tags',['tags'=>array_map(function($t){return['name'=>$t,'status'=>'active'];},$tags)]);$this->stat($id,'submissions');wp_send_json_success(['message'=>$f['success_message'],'redirect'=>$f['redirect_url']]);}
	private function stat($id,$key){$s=get_option(self::STATS,[]);if(!isset($s[$id]))$s[$id]=['views'=>0,'submissions'=>0];$s[$id][$key]=intval($s[$id][$key]??0)+1;update_option(self::STATS,$s,false);}
	public function analytics_page(){$forms=$this->forms();$s=get_option(self::STATS,[]);echo'<div class="wrap emo-wrap"><h1>Form Analytics</h1><div class="emo-card"><table class="widefat striped"><thead><tr><th>Form</th><th>Views</th><th>Submissions</th><th>Conversion</th></tr></thead><tbody>';foreach($forms as$id=>$f){$v=intval($s[$id]['views']??0);$n=intval($s[$id]['submissions']??0);echo'<tr><td>'.esc_html($f['name']).'</td><td>'.$v.'</td><td>'.$n.'</td><td>'.($v?esc_html(number_format_i18n(($n/$v)*100,2)).'%':'0%').'</td></tr>';}echo'</tbody></table></div></div>';}
	public function tools_page(){?><div class="wrap emo-wrap"><h1>Import / Export</h1><div class="emo-grid"><div class="emo-card"><h2>Export</h2><a class="button button-primary" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=emo_export_forms'),'emo_export_forms'));?>">Download JSON</a></div><div class="emo-card"><h2>Import</h2><form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="emo_import_forms"><?php wp_nonce_field('emo_import_forms');?><input required type="file" name="import_file" accept="application/json"><?php submit_button('Import forms');?></form></div></div></div><?php}
	public function export_forms(){if(!current_user_can('manage_options'))wp_die('Unauthorized');check_admin_referer('emo_export_forms');nocache_headers();header('Content-Type: application/json');header('Content-Disposition: attachment; filename=easy-mailchimp-forms-'.gmdate('Y-m-d').'.json');echo wp_json_encode(['version'=>self::VERSION,'forms'=>$this->forms()],JSON_PRETTY_PRINT);exit;}
	public function import_forms(){if(!current_user_can('manage_options'))wp_die('Unauthorized');check_admin_referer('emo_import_forms');$tmp=$_FILES['import_file']['tmp_name']??'';$d=$tmp?json_decode(file_get_contents($tmp),true):null;if(!is_array($d)||!is_array($d['forms']??null))wp_die('Invalid import file.');update_option(self::FORMS,$d['forms'],false);wp_safe_redirect(admin_url('admin.php?page=easy-mailchimp-tools&imported=1'));exit;}
	public function register_block(){wp_register_script('emo-block',plugins_url('assets/js/block.js',__FILE__),['wp-blocks','wp-element','wp-components','wp-block-editor'],self::VERSION,true);wp_localize_script('emo-block','emoBlockData',['forms'=>array_values(array_map(function($f){return['id'=>$f['id'],'name'=>$f['name']];},$this->forms()))]);register_block_type('easy-mailchimp/form',['editor_script'=>'emo-block','render_callback'=>function($a){return$this->shortcode(['id'=>$a['formId']??'']);},'attributes'=>['formId'=>['type'=>'string','default'=>'']]]);}
	public function register_elementor_widget($manager){if(!class_exists('Elementor\\Widget_Base'))return;$plugin=$this;$forms=$this->forms();$class=new class($plugin,$forms) extends \Elementor\Widget_Base{private$plugin,$forms;public function __construct($p,$f,$data=[],$args=null){$this->plugin=$p;$this->forms=$f;parent::__construct($data,$args);}public function get_name(){return'easy_mailchimp_form';}public function get_title(){return'Easy Mailchimp Form';}public function get_icon(){return'eicon-mail';}public function get_categories(){return['general'];}protected function register_controls(){$o=[];foreach($this->forms as$f)$o[$f['id']]=$f['name'];$this->start_controls_section('content');$this->add_control('form_id',['label'=>'Form','type'=>\Elementor\Controls_Manager::SELECT,'options'=>$o]);$this->end_controls_section();}protected function render(){echo$this->plugin->shortcode(['id'=>$this->get_settings_for_display('form_id')]);}};$manager->register($class);}
}
EMO_Premium::instance();
