name: Deploy to WordPress.org SVN

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release
        uses: actions/checkout@v4

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: easy-mailchimp-opt-in
